development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: voting_system_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: voting_system_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: voting_system_production
  username: postgres
  password: postgres
  host: localhost
  port: 5432
